apiVersion: v1
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'istio-prometheus'
      honor_labels: true
      metrics_path: '/federate'
      static_configs:
      - targets:
        - prometheus.istio-system:9090
      metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'workload:(.*)'
        target_label: __name__
        action: replace
      params:
        'match[]':
        - '{__name__=~"workload:(.*)"}'
        - '{__name__=~"pilot(.*)"}'

kind: ConfigMap
metadata:
  labels:
    app: master-prometheus
  name: master-prometheus
